OpenOrderFramework/ViewModels/ShoppingCartViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using OpenOrderFramework.Model.Entity;

namespace OpenOrderFramework.ViewModels
{
    public class ShoppingCartViewModel
    {
        [Key]
        public List<Cart> CartItems { get; set; }
        public decimal CartTotal { get; set; }
    }
}

OpenOrderFramework/Controllers/CheckoutController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using OpenOrderFramework.Configuration;
using OpenOrderFramework.Models;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Reflection;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using log4net;
using OpenOrderFramework.Data.Entitiy;
using OpenOrderFramework.Data.Repository;
using OpenOrderFramework.Model;
using OpenOrderFramework.Model.Entity;
using RestSharp.Authenticators;

namespace OpenOrderFramework.Controllers
{
    [Authorize]
    public class CheckoutController : Controller
    {
        private readonly ILog _log = LogManager.GetLogger(MethodBase.GetCurrentMethod().DeclaringType);
        private MikroOrderDbContext _mikroDbContext = new MikroOrderDbContext();
        private AppConfigurations appConfig = new AppConfigurations();

        public List<String> CreditCardTypes
        {
            get { return appConfig.CreditCardType; }
        }

        //
        // GET: /Checkout/AddressAndPayment
        //public ActionResult AddressAndPayment()
        //{
        //    log4net.Config.XmlConfigurator.Configure();
        //    try
        //    {
        //        using (var dbContext = new MikroOrderDbContext())
        //        {
        //            var previousOrder = dbContext.Orders.FirstOrDefault(x => x.Username == User.Identity.Name);

        //            if (previousOrder != null)
        //                return View(previousOrder);
        //            else
        //                return View();
        //        }
        //    }
        //    catch (Exception ex)
        //    {
        //        _log.Error(ex.Message, ex);
        //        return View();
        //    }

        //}

        //
        // POST: /Checkout/AddressAndPayment
        [HttpPost]
        public async Task<ActionResult> AddressAndPayment(Order model)
        {
            log4net.Config.XmlConfigurator.Configure();
            //string result =  values[9];

            // TryUpdateModel(order);
            //order.CreditCard = result;

            try
            {

                var currentUserId = User.Identity.GetUserId();
                var manager = new UserManager<User>(new UserStore<User>(new MikroOrderDbContext()));
                var store = new UserStore<User>(new MikroOrderDbContext());
                var currentUser = manager.FindById(User.Identity.GetUserId());
                if ( /*order.SaveInfo &&*/ 1 == 2)
                {

                    //var manager = new UserManager<User>(new UserStore<User>(new MikroOrderDbContext()));
                    //var store = new UserStore<User>(new MikroOrderDbContext());
                    //var ctx = store.Context;
                    //var currentUser = manager.FindById(User.Identity.GetUserId());

                    //currentUser.Address = order.Address;

                    //Save this back
                    //http://stackoverflow.com/questions/20444022/updating-user-data-asp-net-identity
                    //var result = await UserManager.UpdateAsync(currentUser);
                    //await ctx.SaveChangesAsync();

                    //await _mikroDbContext.SaveChangesAsync();
                }

                var order = new Order
                {
                    FirstName = User.Identity.Name,
                    LastName = "Test",
                    Address = "Test",
                    Phone = "Test",
                    City = "Test",
                    Username = User.Identity.Name,
                    Email = User.Identity.Name,
                    OrderDate = DateTime.Now,
                    Status = true
                };


                //Save Order
                _mikroDbContext.Orders.Add(order);
                await _mikroDbContext.SaveChangesAsync();
                //Process the order
                var cart = ShoppingCart.GetCart(this.HttpContext);

                var orderItems = cart.GetCartItems();
                order = cart.CreateOrder(order);

                int index = 0;
                var evrakNo = OrderRepository.GetSipEvrakNoFromMikro();
                foreach (var orderItem in orderItems)
                {
                    var stock = StockRepository.GetStockByCode(orderItem.StockCode);
                  

                    var setOrder = SetOrder(orderItem, stock, index, order.OrderId, currentUser.ClientCode);
                    setOrder.sip_evrakno_sira = evrakNo;
                    var success = OrderRepository.InsertOrder(setOrder);

                    if (!success)
                    {
                        var orderToDelete = _mikroDbContext.Orders.FirstOrDefault(f => f.OrderId == order.OrderId);
                        if (orderToDelete != null)
                        {
                            orderToDelete.Status = false;
                            _mikroDbContext.SaveChanges();
                        }

                        var errorDefault = new ErrorPageDefaults()
                        {
                            UserFriendlyMessage = "Sipariş sırasında bir hata oluştu!"
                        };
                        return View("Error", errorDefault);
                    }

                    index++;
                }


                // CheckoutController.SendOrderMessage(order.FirstName, "New Order: " + order.OrderId,order.ToString(order), appConfig.OrderEmail);

                return RedirectToAction("Complete",
                    new { id = order.OrderId });

            }
            catch (Exception ex)
            {
                _log.Error(ex.Message, ex);
                var errorDefault = new ErrorPageDefaults()
                {
                    UserFriendlyMessage = "Sipariş sırasında bir hata oluştu!"
                };
                return View("Error", errorDefault);
            }
        }

        //
        // GET: /Checkout/Complete
        public ActionResult Complete(int id)
        {
            // Validate customer owns this order
            try
            {
                using (var dbContext = new MikroOrderDbContext())
                {
                    bool isValid = dbContext.Orders.Any(o => o.OrderId == id && o.Username == User.Identity.Name);

                    if (isValid)
                    {
                        return View(id);
                    }
                    else
                    {
                        return View("Error");
                    }
                }
            }
            catch (Exception ex)
            {

                throw;
            }

        }

        private async Task SendMailToAdmins()
        {
            //   var emailsToSend = string.Join(", ", participantList.Select(a => a.Email));

            var email = new MailMessage()
            {
                To = { "" },
                Body = "<p> Merhabalar, Toplantı tutanağını ekte bulabilirsiniz. </p>",
                IsBodyHtml = false,
                Subject = "meethink"
            };
            using (var smtpClient = new SmtpClient())
            {
                await smtpClient.SendMailAsync(email);
            }
        }

        private static RestResponse SendOrderMessage(String toName, String subject, String body, String destination)
        {
            RestClient client = new RestClient();
            //fix this we have this up top too
            AppConfigurations appConfig = new AppConfigurations();
            client.BaseUrl = "https://api.mailgun.net/v2";
            client.Authenticator =
                new HttpBasicAuthenticator("api",
                    appConfig.EmailApiKey);
            RestRequest request = new RestRequest();
            request.AddParameter("domain",
                appConfig.DomainForApiKey, ParameterType.UrlSegment);
            request.Resource = "{domain}/messages";
            request.AddParameter("from", appConfig.FromName + " <" + appConfig.FromEmail + ">");
            request.AddParameter("to", toName + " <" + destination + ">");
            request.AddParameter("subject", subject);
            request.AddParameter("html", body);
            request.Method = Method.POST;
            IRestResponse executor = client.Execute(request);
            return executor as RestResponse;
        }

        private OrderEntity SetOrder(Cart orderItem, StockEntity stock, int index, int orderId, string clientCode)
        {
            var order = new OrderEntity()
            {
                sip_RECid_DBCno = 0,
                sip_iptal = false,
                sip_fileid = 21,
                sip_hidden = false,
                sip_kilitli = false,
                sip_degisti = false,
                sip_checksum = 0,
                sip_create_user = 10,
                sip_create_date = DateTime.Now,
                sip_lastup_user = 10,
                sip_lastup_date = DateTime.Now,
                sip_firmano = 0,
                sip_subeno = 0,
                sip_tarih = DateTime.Now,
                sip_teslim_tarih = DateTime.Now,
                sip_tip = 0,
                sip_cins = 0,
                sip_evrakno_seri = "I",
                //sip_evrakno_sira = orderId,//"Webden Gelecek",
                sip_satirno = index,//sipariş edilen ürünün o siparişte kaçıncı olduğu (ilk no 0 dan başlıyor.
                sip_belge_tarih = DateTime.Now,
                sip_musteri_kod = clientCode,//siparişi veren kullanıcı kodu (mikrodaki cari_kod)
                sip_stok_kod = orderItem.StockCode,//sipariş verilen ürünn kodu(mikrodaki stok_kod)
                sip_b_fiyat = orderItem.ListPrice,//satış fiyatı(Mikrodaki stok kartına bağlı satış birim fiyatı),
                sip_miktar = orderItem.Count, //sip miktar
                sip_birim_pntr = 1,
                sip_teslim_miktar = 0,

OpenOrderFramework/Controllers/ShoppingCartController.cs
using OpenOrderFramework.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using log4net;
using Microsoft.AspNet.Identity;
using OpenOrderFramework.Data.Repository;
using OpenOrderFramework.Helper;
using OpenOrderFramework.Model;
using OpenOrderFramework.ViewModels;

namespace OpenOrderFramework.Controllers
{
    [Authorize]
    public class ShoppingCartController : Controller
    {
        private readonly ILog _log = LogManager.GetLogger(MethodBase.GetCurrentMethod().DeclaringType);
        // GET: /ShoppingCart/
        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };
            var clientAmount = AmountHelper.GetClientAmount(User.Identity.Name);
            ViewBag.amount = clientAmount;
            // Return the view
            return View(viewModel);
        }
        //
        // GET: /Store/AddToCart/5
        [HttpPost]
        public ActionResult AddToCart(int id, int quantity)
        {
            // Retrieve the item from the database

            try
            {
                var addedItem = StockRepository.GetProductByStockId(id);
                var clientAmount = AmountHelper.GetClientAmount(User.Identity.Name);

                var userId = User.Identity.GetUserId();
                // Add it to the shopping cart
                var cart = ShoppingCart.GetCart(this.HttpContext);

                var itemsTotalAfterAdd = cart.GetTotal() + (addedItem.ListPrice * quantity);

                if (itemsTotalAfterAdd > clientAmount)
                {
                    // Display the confirmation message
                    var resultsToReturn = new ShoppingCartRemoveViewModel
                    {
                        Message = " Bu işlem için bakiyeniz yeterli değildir.",
                        CartTotal = cart.GetTotal(),
                        CartCount = cart.GetCount(),
                        DeleteId = id,
                        Added = 0
                    };
                    return Json(resultsToReturn);
                }

                int count = cart.AddToCart(addedItem, userId, quantity);

                // Display the confirmation message
                var results = new ShoppingCartRemoveViewModel
                {
                    Message = Server.HtmlEncode(addedItem.StockName) +
                        " sepetinize eklenmiştir.",
                    CartTotal = cart.GetTotal(),
                    CartCount = cart.GetCount(),
                    ItemCount = count,
                    DeleteId = id,
                    Added = 1
                };
                return Json(results);
            }
            catch (Exception ex)
            {
                _log.Error(ex.Message, ex);

                var results = new ShoppingCartRemoveViewModel
                {
                    Message = "Ürün sepetinize eklenirken bir hata oluştu!."
                };

                return Json(results);
            }

            // Go back to the main store page for more shopping
            // return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult UpdateCart(int id, int quantity)
        {
            try
            {
                var addedItem = StockRepository.GetProductByStockId(id);
                var clientAmount = AmountHelper.GetClientAmount(User.Identity.Name);

                var cart = ShoppingCart.GetCart(this.HttpContext);

                var itemTotal = cart.GetItemTotal(addedItem.Id);

                var itemsTotalAfterAdd = cart.GetTotal() + (addedItem.ListPrice * quantity);

                if (itemsTotalAfterAdd > clientAmount)
                {
                    // Display the confirmation message
                    var resultsToReturn = new ShoppingCartRemoveViewModel
                    {
                        Message = " Bu işlem için bakiyeniz yeterli değildir.",
                        CartTotal = cart.GetTotal(),
                        ItemTotal = itemTotal,
                        CartCount = cart.GetCount(),
                        DeleteId = id,
                        Added = 0
                    };
                    return Json(resultsToReturn);
                }

                int count = cart.UpdateCart(addedItem, quantity);

                // Display the confirmation message
                var results = new ShoppingCartRemoveViewModel
                {
                    Message = Server.HtmlEncode(addedItem.StockName) +
                        " sepetinizde güncellenmiştir.",
                    CartTotal = cart.GetTotal(),
                    CartCount = cart.GetCount(),
                    ItemCount = count,
                    DeleteId = id,
                    ItemTotal = cart.GetItemTotal(id),
                    Added = 1
                };
                return Json(results);
            }
            catch (Exception ex)
            {
                _log.Error(ex.Message, ex);
                var results = new ShoppingCartRemoveViewModel
                {
                    Message = "Sepetinizdeki ürünler güncellenirken bir hata oluştu!"
                };
                return Json(results);
            }
        }
        //
        // AJAX: /ShoppingCart/RemoveFromCart/5
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            // Remove the item from the cart
            try
            {
                using (var dbContext = new MikroOrderDbContext())
                {
                    var cart = ShoppingCart.GetCart(this.HttpContext);
                    var cartId = cart.GetCartId(this.HttpContext);
                    // Get the name of the item to display confirmation

                    // Get the name of the album to display confirmation
                    string itemName = dbContext.Carts
                        .Single(item => item.Id == id && item.CartId == cartId).Name;

                    // Remove from cart
                    int itemCount = cart.RemoveFromCart(id);

                    // Display the confirmation message
                    var results = new ShoppingCartRemoveViewModel
                    {
                        Message = Server.HtmlEncode(itemName) +
                            " sepetinizden çıkartılmıştır.",
                        CartTotal = cart.GetTotal(),
                        CartCount = cart.GetCount(),
                        ItemCount = itemCount,
                        DeleteId = id
                    };
                    return Json(results);
                }
            }
            catch (Exception ex)
            {
                _log.Error(ex.Message, ex);
                var results = new ShoppingCartRemoveViewModel
                {
                    Message = "Ürün sepetinizden çıkartılırken bir hata oluştu"
                };
                return Json(results);
            }
        }
        //
        // GET: /ShoppingCart/CartSummary
        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            ViewData["CartCount"] = cart.GetCount();
            return PartialView("CartSummary");
        }
    }
}

OpenOrderFramework/Views/ShoppingCart/CartSummary.cshtml
<a href='@Url.Action("Index", "ShoppingCart")'><strong>Sepet</strong>  <span id="cart-status" class="badge">@ViewData["CartCount"]</span></a>

OpenOrderFramework/Views/ShoppingCart/Index.cshtml
@model OpenOrderFramework.ViewModels.ShoppingCartViewModel
@{
    ViewBag.Title = "Shopping Cart";
}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script type="text/javascript">
    $(function () {
        // Document.ready -> link up remove event handler
        $(".remove").click(function () {
            // Get the id from the link
            var recordToDelete = $(this).attr("data-id");
            if (recordToDelete != '') {
                // Perform the ajax post
                $.post("/ShoppingCart/RemoveFromCart", { "id": recordToDelete },
                    function (data) {
                        // Successful requests get here
                        // Update the page elements
                        if (data.ItemCount == 0) {
                            $('#row-' + data.DeleteId).fadeOut('slow');
                        } else {
                            $('#item-count-' + data.DeleteId).text(data.ItemCount);
                        }
                        $('#cart-total').text(data.CartTotal);
                        $('#update-message').text(data.Message);
                        $('#cart-status').text(data.CartCount);

                    });
            }
        });
        $(".UpdateLink").click(function () {
            // Get the id from the link
            var recordToAdd = $(this).attr("data-id");
            var quantity = $("#" + recordToAdd).val();

            if (recordToAdd != '') {
                // Perform the ajax post
                $.post("/ShoppingCart/UpdateCart", { "id": recordToAdd, "quantity": quantity },
                    function (data) {
                        var added = data.Added;
                        console.log(added);
                        if (added === 0) {
                            $('#update-message').text(data.Message);
                            return false;
                        }
                        $('#cart-status').text(data.CartCount);
                        $('#update-message').text(data.Message);
                        $('#cart-total').text(data.CartTotal);
                        console.log(data.ItemTotal);
                        var selector = "#item-total-" + recordToAdd + " span";
                        $(selector).text(data.ItemTotal);
                    });
            }
        });
    });
</script>
<section id="content">
    <div class="content-wrap">
        <div class="container clearfix">
            @{
                if (Model.CartItems.Count > 0)
                {
                    <div class="table-responsive bottommargin">
                        <div id="update-message">
                        </div>
						<label>Mevcut sipariş krediniz: <strong>@ViewBag.amount</strong></label>
                        @using (Html.BeginForm("AddressAndPayment", "Checkout", FormMethod.Post, new { @id = "orderform", @class = "nobottommargin" }))

                        {
                            <table class="table cart">
                                <thead>
                                    <tr>
                                        <th class="cart-product-remove">&nbsp;</th>
                                        <th class="cart-product-name">Ürün</th>
                                        <th class="cart-product-price">Birim Fiyat</th>
                                        <th class="cart-product-quantity">Miktar</th>
                                        <th class="cart-product-subtotal">Total</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.CartItems)
                                    {
                                        <tr class="cart_item" id="row-@item.Id">
                                            <td class="cart-product-remove">
                                                <a href="#" class="remove" title="Sepetten çıkar" data-id="@item.Id"><i class="icon-trash2"></i></a>
                                            </td>
                                            <td class="cart-product-name">
                                                @Html.ActionLink(item.Name, "Details", "Store", new { id = item.Id }, null)
                                            </td>
                                            <td class="cart-product-price">
                                                <span class="amount">@item.ListPrice</span>
                                            </td>
                                            <td class="cart-product-quantity" id="item-count-@item.Id">
                                                <input id="@item.ItemId" name="Count" type="number" style="width: 60px" value="@item.Count" />
                                            </td>
                                            <td class="cart-product-subtotal" id="item-total-@item.ItemId">
                                                <span class="amount">@item.Total</span>
                                            </td>
                                            <td>
                                                <a href="#" class="UpdateLink"
                                                   data-id="@item.ItemId">
                                                    Sepeti Güncelle
                                                </a>
                                            </td>
                                        </tr>
                                    }
                                    <tr>
                                        <td>Toplam</td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td id="cart-total">@Model.CartTotal</td>
                                    </tr>
                                    <tr class="cart_item">
                                        <td colspan="6">
                                            <div class="row clearfix">
                                                <div class="col-md-12 col-xs-12 nopadding">
                                                    @*<button href="shop.html" style="text-transform: none;" class="button button-3d notopmargin fright" onclick="location.href = '@Url.Action("AddressAndPayment", "Checkout")'">Sipariş ver</button>*@
                                                    <button type="submit" class="button button-3d notopmargin fright" style="text-transform: initial;">Sipariş ver</button>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        }
                    </div>
                }
                else
                {
                    <div>
                        <p>
                            Sepetinizde ürün yoktur.
                        </p>
                    </div>
                }
            }
        </div>
    </div>
</section>