OpenOrderFramework/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using log4net;
using OpenOrderFramework.Data.Repository;
using OpenOrderFramework.Helper;
using OpenOrderFramework.Model;
using PagedList.Mvc;
using PagedList;
using OpenOrderFramework.Models;
using OpenOrderFramework.Model.Entity;

namespace OpenOrderFramework.Controllers
{
    [Authorize]
    public class ItemsController : Controller
    {
        private MikroOrderDbContext db = new MikroOrderDbContext();
        private readonly ILog _log = LogManager.GetLogger(MethodBase.GetCurrentMethod().DeclaringType);
        // GET: Items
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.PriceSortParm = sortOrder == "Price" ? "price_desc" : "Price";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            //var items = StockRepository.GetStocks();
            try
            {
                var items = StockRepository.GetStocks();

                if (items == null || items.Count < 1)
                {
                    var errorDefault=new ErrorPageDefaults()
                    {
                        UserFriendlyMessage = "Güncelleme yapılmaktadır. Kısa bir süre sonra tekrar yayına açılacağız"
                    };
                    return View("Error", errorDefault);
                }

                if (!String.IsNullOrEmpty(searchString))
                {
                    items = items.Where(s => s.StockName.ToUpper().Contains(searchString.ToUpper()) || s.StockCode.ToUpper().Contains(searchString.ToUpper())).ToList();
                }
                switch (sortOrder)
                {
                    case "name_desc":
                        items = items.OrderByDescending(s => s.StockName).ToList();
                        break;
                    case "Price":
                        items = items.OrderBy(s => s.ListPrice).ToList();
                        break;
                    case "price_desc":
                        items = items.OrderByDescending(s => s.ListPrice).ToList();
                        break;
                    default:  // Name ascending 
                        items = items.OrderBy(s => s.StockName).ToList();
                        break;
                }

                var clientAmount = AmountHelper.GetClientAmount(User.Identity.Name);
                ViewBag.amount = clientAmount;

                int pageSize = 10;
                int pageNumber = (page ?? 1);

                return View(items.ToPagedList(pageNumber, pageSize));
            }
            catch (Exception ex)
            {
                _log.Error(ex.Message, ex);
            }

            return View();

            //var items = db.Items.Include(i => i.Catagorie);
            //return View(await items.ToListAsync());
        }

        // GET: Items/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            using (var dbContext = new MikroOrderDbContext())
            {
                Item item = await dbContext.Items.FindAsync(id);
                if (item == null)
                {
                    return HttpNotFound();
                }
                return View(item);
            }

        }

        // GET: Items/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            // ViewBag.CatagorieId = new SelectList(db.Catagories, "ID", "Name");
            return View();
        }

        // POST: Items/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Create(Item item)
        {
            if (ModelState.IsValid)
            {
                db.Items.Add(item);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            //ViewBag.CatagorieId = new SelectList(db.Catagories, "ID", "Name", item.CatagorieId);
            return View(item);
        }

        // GET: Items/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = await db.Items.FindAsync(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            // ViewBag.CatagorieId = new SelectList(db.Catagories, "ID", "Name", item.CatagorieId);
            return View(item);
        }

        // POST: Items/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Edit(Item item)
        {
            if (ModelState.IsValid)
            {
                db.Entry(item).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            //  ViewBag.CatagorieId = new SelectList(db.Catagories, "ID", "Name", item.CatagorieId);
            return View(item);
        }

        // GET: Items/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = await db.Items.FindAsync(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Item item = await db.Items.FindAsync(id);
            db.Items.Remove(item);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OpenOrderFramework/Controllers/ShoppingCartController.cs
using OpenOrderFramework.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using log4net;
using Microsoft.AspNet.Identity;
using OpenOrderFramework.Data.Repository;
using OpenOrderFramework.Helper;
using OpenOrderFramework.Model;
using OpenOrderFramework.ViewModels;

namespace OpenOrderFramework.Controllers
{
    [Authorize]
    public class ShoppingCartController : Controller
    {
        private readonly ILog _log = LogManager.GetLogger(MethodBase.GetCurrentMethod().DeclaringType);
        // GET: /ShoppingCart/
        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };
            var clientAmount = AmountHelper.GetClientAmount(User.Identity.Name);
            ViewBag.amount = clientAmount;
            // Return the view
            return View(viewModel);
        }
        //
        // GET: /Store/AddToCart/5
        [HttpPost]
        public ActionResult AddToCart(int id, int quantity)
        {
            // Retrieve the item from the database

            try
            {
                var addedItem = StockRepository.GetProductByStockId(id);
                var clientAmount = AmountHelper.GetClientAmount(User.Identity.Name);

                var userId = User.Identity.GetUserId();
                // Add it to the shopping cart
                var cart = ShoppingCart.GetCart(this.HttpContext);

                var itemsTotalAfterAdd = cart.GetTotal() + (addedItem.ListPrice * quantity);

                if (itemsTotalAfterAdd > clientAmount)
                {
                    // Display the confirmation message
                    var resultsToReturn = new ShoppingCartRemoveViewModel
                    {
                        Message = " Bu işlem için bakiyeniz yeterli değildir.",
                        CartTotal = cart.GetTotal(),
                        CartCount = cart.GetCount(),
                        DeleteId = id,
                        Added = 0
                    };
                    return Json(resultsToReturn);
                }

                int count = cart.AddToCart(addedItem, userId, quantity);

                // Display the confirmation message
                var results = new ShoppingCartRemoveViewModel
                {
                    Message = Server.HtmlEncode(addedItem.StockName) +
                        " sepetinize eklenmiştir.",
                    CartTotal = cart.GetTotal(),
                    CartCount = cart.GetCount(),
                    ItemCount = count,
                    DeleteId = id,
                    Added = 1
                };
                return Json(results);
            }
            catch (Exception ex)
            {
                _log.Error(ex.Message, ex);

                var results = new ShoppingCartRemoveViewModel
                {
                    Message = "Ürün sepetinize eklenirken bir hata oluştu!."
                };

                return Json(results);
            }

            // Go back to the main store page for more shopping
            // return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult UpdateCart(int id, int quantity)
        {
            try
            {
                var addedItem = StockRepository.GetProductByStockId(id);
                var clientAmount = AmountHelper.GetClientAmount(User.Identity.Name);

                var cart = ShoppingCart.GetCart(this.HttpContext);

                var itemTotal = cart.GetItemTotal(addedItem.Id);

                var itemsTotalAfterAdd = cart.GetTotal() + (addedItem.ListPrice * quantity);

                if (itemsTotalAfterAdd > clientAmount)
                {
                    // Display the confirmation message
                    var resultsToReturn = new ShoppingCartRemoveViewModel
                    {
                        Message = " Bu işlem için bakiyeniz yeterli değildir.",
                        CartTotal = cart.GetTotal(),
                        ItemTotal = itemTotal,
                        CartCount = cart.GetCount(),
                        DeleteId = id,
                        Added = 0
                    };
                    return Json(resultsToReturn);
                }

                int count = cart.UpdateCart(addedItem, quantity);

                // Display the confirmation message
                var results = new ShoppingCartRemoveViewModel
                {
                    Message = Server.HtmlEncode(addedItem.StockName) +
                        " sepetinizde güncellenmiştir.",
                    CartTotal = cart.GetTotal(),
                    CartCount = cart.GetCount(),
                    ItemCount = count,
                    DeleteId = id,
                    ItemTotal = cart.GetItemTotal(id),
                    Added = 1
                };
                return Json(results);
            }
            catch (Exception ex)
            {
                _log.Error(ex.Message, ex);
                var results = new ShoppingCartRemoveViewModel
                {
                    Message = "Sepetinizdeki ürünler güncellenirken bir hata oluştu!"
                };
                return Json(results);
            }
        }
        //
        // AJAX: /ShoppingCart/RemoveFromCart/5
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            // Remove the item from the cart
            try
            {
                using (var dbContext = new MikroOrderDbContext())
                {
                    var cart = ShoppingCart.GetCart(this.HttpContext);
                    var cartId = cart.GetCartId(this.HttpContext);
                    // Get the name of the item to display confirmation

                    // Get the name of the album to display confirmation
                    string itemName = dbContext.Carts
                        .Single(item => item.Id == id && item.CartId == cartId).Name;

                    // Remove from cart
                    int itemCount = cart.RemoveFromCart(id);

                    // Display the confirmation message
                    var results = new ShoppingCartRemoveViewModel
                    {
                        Message = Server.HtmlEncode(itemName) +
                            " sepetinizden çıkartılmıştır.",
                        CartTotal = cart.GetTotal(),
                        CartCount = cart.GetCount(),
                        ItemCount = itemCount,
                        DeleteId = id
                    };
                    return Json(results);
                }
            }
            catch (Exception ex)
            {
                _log.Error(ex.Message, ex);
                var results = new ShoppingCartRemoveViewModel
                {
                    Message = "Ürün sepetinizden çıkartılırken bir hata oluştu"
                };
                return Json(results);
            }
        }
        //
        // GET: /ShoppingCart/CartSummary
        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            ViewData["CartCount"] = cart.GetCount();
            return PartialView("CartSummary");
        }
    }
}

OpenOrderFramework/Views/Items/Create.cshtml
@model OpenOrderFramework.Model.Entity.Item
@using OpenOrderFramework.Extensions

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Items", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Item</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CatagorieId, "CatagorieId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CatagorieId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CatagorieId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

OpenOrderFramework/Views/Items/Delete.cshtml
@model OpenOrderFramework.Model.Entity.Item

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Item</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Catagorie.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Catagorie.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ItemPictureUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemPictureUrl)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

OpenOrderFramework/Views/Items/Details.cshtml
@model OpenOrderFramework.Model.Entity.Item

@{
    ViewBag.Title = "Details";
}


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script type="text/javascript">
    $(function () {
        // Document.ready -> link up remove event handler
        $(".AddLink").click(function () {
            // Get the id from the link
            var recordToAdd = $(this).attr("data-id");
            if (recordToAdd != '') {
                // Perform the ajax post
                $.post("/ShoppingCart/AddToCart", { "id": recordToAdd },
                    function (data) {
                        $('#cart-status').text(data.CartCount);
                    });
            }
        });
    });
</script>

<!-- Button trigger modal -->

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

    <div aria-hidden="true" class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <strong>An item was added to your cart.</strong> To check out now simply <a href="#" class="alert-link">click here</a>.
    </div>

    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Confirm check out.</h4>
            </div>
            <div class="modal-body">
                <p>Would you like to check out or keep shopping?</p>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Continue</button>
                <button type="submit" class="btn btn-primary" onclick="location.href='@Url.Action("Index", "ShoppingCart")'">Check Out</button>
            </div>
        </div>
    </div>
</div>





<h2>Details</h2>

<div>
    <h4>Item</h4>
    <hr />
    <dl class="dl-horizontal">
        <img src="@Url.Action("RenderImage", new { id = Model.ID})" />
    </dl>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Catagorie.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Catagorie.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ItemPictureUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemPictureUrl)
        </dd>

    </dl>
</div>
<p>
    <a href="#" class="AddLink"
       data-id="@Model.ID" data-toggle="modal" data-target="#myModal">
        Add
        to cart
    </a>
    @if (Request.IsAuthenticated && User.IsInRole("Admin"))
    {
        @Html.ActionLink("Edit", "Edit", new { id = Model.ID })
        
    }
     
    @Html.ActionLink("Back to List", "Index")
</p>

OpenOrderFramework/Views/Items/Edit.cshtml
@model OpenOrderFramework.Model.Entity.Item

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Item</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)
        <div class="form-group">
            @Html.LabelFor(model => model.CatagorieId, "CatagorieId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CatagorieId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CatagorieId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ItemPictureUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ItemPictureUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ItemPictureUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

OpenOrderFramework/Views/Items/Index.cshtml
@model PagedList.IPagedList<OpenOrderFramework.Data.Entitiy.ProductEntity>
@using PagedList.Mvc;
@*<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />*@
@{
    ViewBag.Title = "Food";
}

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script type="text/javascript">
    $(function () {
        // Document.ready -> link up remove event handler
        $(".AddLink").click(function () {
            $('#update-message').text("");
            // Get the id from the link
            var recordToAdd = $(this).attr("data-id");

            var quantity = $("#" + recordToAdd).val();
            if (quantity <= 0) {
                alert("En az 1 ürün ekleyiniz");
                return false;
            }



            if (recordToAdd != '') {
                // Perform the ajax post
                $.post("/ShoppingCart/AddToCart", { "id": recordToAdd, "quantity": quantity },
                    function (data) {
                        $('#cart-status').text(data.CartCount);
                        var added = data.Added;
                        if (added === 0) {
                            $("#myModal").modal('hide');
                            $('#update-message').text(data.Message);
                            return false;
                        } else {

                            $("#myModal").modal('show');
                        }
                    });
            }
        });
    })
</script>
<!-- Button trigger modal -->
<section id="content">
    <div class="content-wrap" style="padding-top: 40px">
        <div class="container clearfix">
            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div aria-hidden="true" class="alert alert-dismissable alert-success">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <strong>Ürün sepetinize eklenmiştir.</strong> @*To check out now simply <a href="#" class="alert-link">click here</a>*@.
                </div>
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            <h4 class="modal-title">Siparişi doğrula</h4>
                        </div>
                        <div class="modal-body">
                            <p>Alışverişe devam etmek ister misiniz??</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Devam et</button>
                            <button type="submit" class="btn btn-primary" onclick="location.href='@Url.Action("Index", "ShoppingCart")'">Sipariş ver sayfası git</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="bs-docs-section">
                <div class="row">
                    @using (Html.BeginForm("Index", "Items", FormMethod.Get))
            {

                        <div class="form-group">
                            <div id="update-message" style="color: red">
                            </div>
							<label>Mevcut sipariş krediniz: <strong>@ViewBag.amount</strong></label>
                            <div class="input-group">
                                <span class="input-group-addon">Ürün Ara: </span>
                                @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "required sm-form-control", @style = " width:200px; " })
                                <span class="input-group-btn">
                                    <input type="submit" class="button button-3d nomargin" value="Ara" />
                                </span>
                            </div>
                        </div>
                    }
                </div>
            </div>
            <table class="table" style="font-family: sans-serif;">
                <tr>
                    <th>
                        Stok Kodu
                    </th>
                    <th>
                        @Html.ActionLink("Ürün", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
                    </th>
                    @*<th>
                        Kategori
                    </th>*@
                    <th>
                        @Html.ActionLink("Satış Fiyatı", "Index", new { sortOrder = ViewBag.PriceSortParm, currentFilter = ViewBag.CurrentFilter })
                    </th>
	                <th>
		                Miktar
	                </th>
	                <th>
		                Birim
	                </th>
                    <th></th>
                </tr>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.StockCode)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.StockName)
                        </td>
                        @*<td>
                            @Html.DisplayFor(modelItem => item.Category)
                        </td>*@
                        <td>
                            @Html.DisplayFor(modelItem => item.ListPrice)
                        </td>
	                    <td>
		                    <input type="number" id="@item.Id" style="width: 60px;" value="1" />
	                    </td>
	                    <td>
		                    @Html.DisplayFor(modelItem => item.Unit)
	                    </td>
                        <td>
                            @if (item.HaveCount > 1)
                            {
                                <a href="#" class="AddLink"
                                   data-id="@item.Id">
                                    Sepete Ekle
                                </a>
                            }
                            else
                            {
                                <label style="color: red">Stok Yok</label>
                            }

                            <!--@Html.ActionLink("Sepete Ekle", "AddToCart", "ShoppingCart", new {id = item.Id}, new {htmlAttributes = new {@data_toggle = "modal", @data_target = "#myModal"}})-->
                            @*@Html.ActionLink("Details", "Details", new {id = item.Id})*@
                            @*@if (Request.IsAuthenticated && User.IsInRole("Admin"))
                                {
                                    @Html.ActionLink("Edit", "Edit", new { id = item.Id })
                                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                                }*@
                        </td>
                    </tr>
                }
            </table>
            <br/>
            @Model.PageCount sayfadan @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber).
            @*Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount*@
            @Html.PagedListPager(Model, page => Url.Action("Index",
new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
        </div>
    </div>

</section>